package com.jusfoun.dao.mapper;

import com.jusfoun.dao.BaseMapper;
import com.jusfoun.model.RoleHasModuleExample;
import com.jusfoun.model.RoleHasModuleKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleHasModuleMapper extends BaseMapper<RoleHasModuleKey, RoleHasModuleExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    int countByExample(RoleHasModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    int deleteByExample(RoleHasModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    @Delete({
        "delete from role_has_module",
        "where roleId = #{roleId,jdbcType=INTEGER}",
          "and moduleId = #{moduleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(RoleHasModuleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    @Insert({
        "insert into role_has_module (roleId, moduleId)",
        "values (#{roleId,jdbcType=INTEGER}, #{moduleId,jdbcType=INTEGER})"
    })
    int insert(RoleHasModuleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    int insertSelective(RoleHasModuleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    List<RoleHasModuleKey> selectByExample(RoleHasModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoleHasModuleKey record, @Param("example") RoleHasModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    int updateByExample(@Param("record") RoleHasModuleKey record, @Param("example") RoleHasModuleExample example);
}
