package com.jusfoun.dao.mapper;

import com.jusfoun.dao.BaseMapper;
import com.jusfoun.model.UserHasRoleExample;
import com.jusfoun.model.UserHasRoleKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserHasRoleMapper extends BaseMapper<UserHasRoleKey, UserHasRoleExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    int countByExample(UserHasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    int deleteByExample(UserHasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    @Delete({
        "delete from user_has_role",
        "where userId = #{userId,jdbcType=INTEGER}",
          "and roleId = #{roleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UserHasRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    @Insert({
        "insert into user_has_role (userId, roleId)",
        "values (#{userId,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER})"
    })
    int insert(UserHasRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    int insertSelective(UserHasRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    List<UserHasRoleKey> selectByExample(UserHasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserHasRoleKey record, @Param("example") UserHasRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    int updateByExample(@Param("record") UserHasRoleKey record, @Param("example") UserHasRoleExample example);
}
