server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
#  context-path: /demo

debug: true

logging:
  file: logs/spring-boot-example.log
  level:
    org.springframework: info
    org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer: info
    com.jusfoun: debug

spring:
  mail:
    host: smtp.qiye.163.com
    username: liutiyang@jusfoun.com
    password: