server:
  port: 8081

debug: true

logging:
  file: logs/log-config.log
  level:
    org.springframework: info
    org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer: info
    com.jusfoun: debug
