package com.jusfoun.model;

import java.io.Serializable;
import java.util.Date;

public class Module implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.moduleId
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.moduleName
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.moduleParentId
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    private Integer moduleParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.moduleUrl
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    private String moduleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.status
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.createTime
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.updateTime
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table module
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public Module(Integer moduleId, String moduleName, Integer moduleParentId, String moduleUrl, Byte status, Date createTime, Date updateTime) {
        this.moduleId = moduleId;
        this.moduleName = moduleName;
        this.moduleParentId = moduleParentId;
        this.moduleUrl = moduleUrl;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public Module() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.moduleId
     *
     * @return the value of module.moduleId
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.moduleId
     *
     * @param moduleId the value for module.moduleId
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.moduleName
     *
     * @return the value of module.moduleName
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.moduleName
     *
     * @param moduleName the value for module.moduleName
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.moduleParentId
     *
     * @return the value of module.moduleParentId
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public Integer getModuleParentId() {
        return moduleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.moduleParentId
     *
     * @param moduleParentId the value for module.moduleParentId
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public void setModuleParentId(Integer moduleParentId) {
        this.moduleParentId = moduleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.moduleUrl
     *
     * @return the value of module.moduleUrl
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.moduleUrl
     *
     * @param moduleUrl the value for module.moduleUrl
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.status
     *
     * @return the value of module.status
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.status
     *
     * @param status the value for module.status
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.createTime
     *
     * @return the value of module.createTime
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.createTime
     *
     * @param createTime the value for module.createTime
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.updateTime
     *
     * @return the value of module.updateTime
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.updateTime
     *
     * @param updateTime the value for module.updateTime
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Wed May 24 10:47:07 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", moduleId=").append(moduleId);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", moduleParentId=").append(moduleParentId);
        sb.append(", moduleUrl=").append(moduleUrl);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}