package com.jusfoun.model;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleId
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleName
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleDesc
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleParentId
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private Integer roleParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.permissionName
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.status
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.createTime
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.updateTime
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public Role(Integer roleId, String roleName, String roleDesc, Integer roleParentId, String permissionName, Byte status, Date createTime, Date updateTime) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.roleParentId = roleParentId;
        this.permissionName = permissionName;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public Role() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleId
     *
     * @return the value of role.roleId
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleId
     *
     * @param roleId the value for role.roleId
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleName
     *
     * @return the value of role.roleName
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleName
     *
     * @param roleName the value for role.roleName
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleDesc
     *
     * @return the value of role.roleDesc
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleDesc
     *
     * @param roleDesc the value for role.roleDesc
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleParentId
     *
     * @return the value of role.roleParentId
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public Integer getRoleParentId() {
        return roleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleParentId
     *
     * @param roleParentId the value for role.roleParentId
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public void setRoleParentId(Integer roleParentId) {
        this.roleParentId = roleParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.permissionName
     *
     * @return the value of role.permissionName
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.permissionName
     *
     * @param permissionName the value for role.permissionName
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.status
     *
     * @return the value of role.status
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.status
     *
     * @param status the value for role.status
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.createTime
     *
     * @return the value of role.createTime
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.createTime
     *
     * @param createTime the value for role.createTime
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.updateTime
     *
     * @return the value of role.updateTime
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.updateTime
     *
     * @param updateTime the value for role.updateTime
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Wed May 24 10:47:32 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleDesc=").append(roleDesc);
        sb.append(", roleParentId=").append(roleParentId);
        sb.append(", permissionName=").append(permissionName);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}