package com.jusfoun.model;

import java.io.Serializable;

public class RoleHasModuleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_module.roleId
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_module.moduleId
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    public RoleHasModuleKey(Integer roleId, Integer moduleId) {
        this.roleId = roleId;
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    public RoleHasModuleKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_module.roleId
     *
     * @return the value of role_has_module.roleId
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_module.roleId
     *
     * @param roleId the value for role_has_module.roleId
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_module.moduleId
     *
     * @return the value of role_has_module.moduleId
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_module.moduleId
     *
     * @param moduleId the value for role_has_module.moduleId
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_module
     *
     * @mbggenerated Wed May 24 10:49:22 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", moduleId=").append(moduleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}