package com.jusfoun.model;

import java.io.Serializable;

public class UserHasRoleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_has_role.userId
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_has_role.roleId
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    public UserHasRoleKey(Integer userId, Integer roleId) {
        this.userId = userId;
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    public UserHasRoleKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_has_role.userId
     *
     * @return the value of user_has_role.userId
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_has_role.userId
     *
     * @param userId the value for user_has_role.userId
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_has_role.roleId
     *
     * @return the value of user_has_role.roleId
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_has_role.roleId
     *
     * @param roleId the value for user_has_role.roleId
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_has_role
     *
     * @mbggenerated Wed May 24 10:49:36 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}